### ISSUE TITLE
document spark

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/docs#446]
```[tasklist]
### Tasks
- [ ] explain that timings is gone (and why)
- [ ] explain what spark is
- [x] link to spark docs for usage
- [ ] explain `paper.startSparkBackgroundProfilerImmediately` (and add it to the system property page too, can link back to spark page)
- [ ] explain how to change the spark version
- [ ] add spark config/folder to the folder view
- [ ] add spark enable option to paper config page
```
